#XZQcreat.o:XZQcreat.c
#	gcc XZQcreat.c -o XZQcreat.o
*.o:*.cpp
	g++ duotai.cpp -o duotai.o
#	gcc XZQwrite.c -o XZQwrite
#XZQcreat.o:XZQcreat.c
#	gcc XZQcreat.c -o XZQcreat.o
#XZQcreat.o:XZQcreat.c
#	gcc XZQcreat.c -o XZQcreat.o

.PHONY:clean
clean:
	-rm ./*.o 
